version: "3.9"
services:
  web:
    image: "lidatong/aux-aptos-graphql"
    ports:
      - "4000:4000"
  aptos-mainnet-fullnode:
    image: "aptoslabs/validator:mainnet"
    ports:
      - "8080:8080"
      - "9101:9101"
      - "6180:6180"
    volumes:
      - .:/opt/aptos/etc
      - ./data:/opt/aptos/data
    working_dir:
      - /opt/aptos/etc
    command:
      - aptos-node -f /opt/aptos/etc/fullnode.yaml
  redis:
    image: "redis:alpine"
