[package]
name = 'deployer'
version = '1.0.0'

[addresses]
AptosFramework = "0x1"
aux_deployer = "_"

[dev-addresses]
aux_deployer = "0x12345"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '23d258d1f2440267f866eeb27f9830be48682af8'
subdir = 'aptos-move/framework/aptos-framework'
